### ISSUE TITLE
Works on El Capitan?

### ISSUE THREAD

**Issue by diego898** [PeterKaminski09/baskup#10]
I just tried this on el capitan, and after making sure all of my contacts are on my mac, I then click backup and show files. It takes me to a directory filled with files without extensions and no folders. Some strange behaviors:
- No folders? What happened to my images? 
- No file extensions? Seems they should all be `.txt`? 
- Group chats have names like: `chat` followed immediately by 18 numbers. 
- Some contacts are separated having two separate files like `+xxxxxx` and `contactemail@email.com`. 
- How do I find a group chat between three specific people?

**Comment by PeterKaminski09** [comment]
No folders? What happened to my images? -> This feature is not available on the desktop version-- it is going to be added, but available to users that donate
No file extensions? Seems they should all be .txt? -> They are text files, just don't have the extension. This can be added 
Group chats have names like: chat followed immediately by 18 numbers. -> This is the standard way Apple stores group chats. Nothing I can do here. 
Some contacts are separated having two separate files like +xxxxxx and contactemail@email.com.
How do I find a group chat between three specific people? -> Sometimes an iMessage is sent and received from the email address, sometimes it's the number. Again, an inconvenience I can't avoid.

**Comment by diego898** [comment]
Ok. Im not sure what you mean y desktop version? Is there another version? Do you mean just the plain bash script? If so, can I just use the bash script directly?

The behavior of this app doesnt exactly match the readme. The readme says: 
* `as well as your audio and image files`.
* `Each folder will be named after the contact's phone number`
* `Within each directory you will find a directory for the attachments from that message, and the actual message text file.`

You might want to update to reflect that there will be paid features.

**Comment by PeterKaminski09** [comment]
Ah, this repository is for a bash script. 

There is a desktop version available at www.peterkaminski09.github.io/baskup 

The readme is for the bash script.

**Comment by diego898** [comment]
ok thank you for clarifying!

**Comment by jseiff** [comment]
In the group chat files, there is no differentiation in who says what.

**Comment by PeterKaminski09** [comment]
@jseiff I'm looking into that capability for the mac version.
