### ISSUE TITLE
No Attachment Folder

### ISSUE THREAD

**Issue by zuliandres** [PeterKaminski09/baskup#14]
Hey, 
this is so great, I had been looking for this. Unfortunately, when running the app on my Macbook it did not create a back up of the attachments on the messages. It's unfortunate because I was looking forward to viewing all files shared with specific contacts. 
I am also looking for a way to do this directly from an iPhone backup, not the macOS Messages app but the actual text messages on my phone. Any ideas or references?
Thanks again Peter! Great job

**Comment by PeterKaminski09** [comment]
Attachments is something that will be added to future versions of the MacOS app. For now, you can use the bash script version available on Github to backup attachments.
