### ISSUE TITLE
No longer shows timestamps on High Sierra

### ISSUE THREAD

**Issue by Brlgomez** [PeterKaminski09/baskup#15]
It just shows blank after @

**Comment by Pezmc** [comment]
It seems, at least in macOS High Sierra that dates have increased in size by a factor of 10.

For example: 

- 2017-10-18 10:29:34, is now stored as 530011774000000000.
- To get the true time, you need to divide by 1000000000
 - And then add 2001-01-01 in UNIX time (978307200).

i.e.

- 530011774000000000 / 1000000000 = 530011774
- 530011774 + 978307200 = 1508318974
- 1508318974 => Wednesday, 18 October 2017 09:29:34

**Comment by PeterKaminski09** [comment]
Working on this right now. Thanks for opening the issue

**Comment by virpatel524** [comment]
Thank you for your dedication. Keep up the good work.

**Comment by PeterKaminski09** [comment]
Think I have this fixed. Let me know if this doesn't work for you

https://dl.orangedox.com/baskup-v1.1?dl=1
