### ISSUE TITLE
Extract maps location

### ISSUE THREAD

**Issue by prohtex** [PeterKaminski09/baskup#2]
I'm looking to extract a maps location someone sent me in a message. I used this tool to extract the chat transcript, but the line where they sent the pin is empty. Is there any way to do this? Thanks!

**Comment by PeterKaminski09** [comment]
Did you check the corresponding attachments folder?

On Thu, Sep 17, 2015 at 3:50 PM, PeterKaminski09/baskup
<reply@reply.github.com>
wrote:
I'm looking to extract a maps location someone sent me in a message. I used this
tool to extract the chat transcript, but the line where they sent the pin is
empty. Is there any way to do this? Thanks!

**Comment by prohtex** [comment]
Aha - there it was! Thanks for offering this excellent script. Unrelatedly, the script dumped a bunch of 0k txt files in my home dir.
