### ISSUE TITLE
not sure how to run script file

### ISSUE THREAD

**Issue by loopernow** [PeterKaminski09/baskup#20]
Not a programmer, not sure how to download the file from this page. I click on Download ZIP but it just downloads an empty 3kb directory called "backup-master." I copied and pasted the script file and could run it from the command line but apparently it needs other files. It gave me an error ("cannot execute binary file").

I have the macOS app too but it doesn't backup message attachments, which is really what I want to do.

**Comment by PeterKaminski09** [comment]
The macOS app should backup attachments. Make sure that this is selected. To use the backup-master script, you'll need to open the Terminal application on mac and follow these directions https://asciinema.org/a/t8RP4RHnOYCtbUf0BJDv7RIcU

![screen shot 2017-12-23 at 12 03 56 pm](https://user-images.githubusercontent.com/5935411/34321631-6732b790-e7d9-11e7-9343-35fa7bd61291.JPEG)

**Comment by PeterKaminski09** [comment]
From terminal:
Run: cd (path of the downloaded baskup folder, i.e cd ~/Downloads/baskup-master)
2a. Run: bash baskup.sh to only backup messages 💬
2b. Run: bash baskup.sh -a to backup messages AND attachments 💬 + 📎
