### ISSUE TITLE
Baskup breaks on MacOS Mojave 10.14 Beta (18A377a)

### ISSUE THREAD

**Issue by otisdog8** [PeterKaminski09/baskup#23]
Though this has been occurring throughout Mojave, I have noticed that baskup will crash (the graphical app) and that the shell script will return "unable to open database file". I am using baskup 2.0 and the latest version of the shell script.

**Comment by otisdog8** [comment]
Also I understand that it might be unfeasible to fix, and if so, I respect that, as Apple might have radically changed the database structure.

**Comment by otisdog8** [comment]
Okay I got it to work on a local backup (that I grabbed from my phone). Texts and iMessages copy over fine (I think), but attachments don't work (as it is a mobile backup)

**Comment by otisdog8** [comment]
I eventually got it to work by disabling SIP. Your method is _much_ more effective.

**Comment by PeterKaminski09** [comment]
Thanks for looking into it! I'll update the docs to reflect this new set-up step.
