### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by ArundelDesigns** [PeterKaminski09/baskup#3]
Thanks for making this tool Peter. For whatever reason Adium's import is failing me completely, and this does the trick.

Adding the feature of date/time stamping the transcripts each line would be a huge benefit. 

It is very simple to customise baskup.sh, but I am curious why the decision was made to hardcode the script folder.

**Comment by PeterKaminski09** [comment]
Timestamp has been added. I'm in the process of making this into a full OS X application, and integrating contacts in. Thanks for the patience. 

Peter

**Comment by PeterKaminski09** [comment]
Check out the new OS X application at  http://peterkaminski09.github.io/baskup/
