### ISSUE TITLE
Relationship between baskup.app & baskup.sh

### ISSUE THREAD

**Issue by seamusdemora** [PeterKaminski09/baskup#37]
I've installed `baskup.app` on my system. I want to submit a Pull Request to add a feature I've implemented in `awk`, but the source is available for only `baskup.sh`. It seems that `baskup.sh` doesn't exist on my system, and so I'm unclear as to if and how a Pull Request against `baskup.sh` gets incorporated in `baskup.app`?

**Comment by PeterKaminski09** [comment]
Baskup.sh is the shell script this repo contains. 

Baskup.app is from the Mac app I built out a few years ago. That’s not currently open source, so they’re unrelated.

**Comment by seamusdemora** [comment]
Hmm... guess I've been laboring under a false impression. I don't suppose you've documented any diffs in how the app & the script are different?
