### ISSUE TITLE
Does it work with Yosemite?

### ISSUE THREAD

**Issue by cvpeck** [PeterKaminski09/baskup#5]
Running under Yosemite I get (asterisks added to protect the innocent)-

user (master *) baskup-master $ bash baskup.sh
<open file '/tmp/dumped.txt', mode 'r' at 0x104481810>
mkdir: +614*******: File exists
mkdir: Attachments: File exists
backUpMessages.sh: line 44: iMessage;-;+614*******: command not found
usage: mkdir [-pv] [-m mode] directory ...
mkdir: Attachments: File exists
backUpMessages.sh: line 44: +614*********: command not found
mkdir: can***********@126.com: File exists
mkdir: Attachments: File exists
backUpMessages.sh: line 44: iMessage;-;can**********@126.com: command not found

etc

**Comment by PeterKaminski09** [comment]
I haven't looked at this project for a while, but it was written on Yosemite.
Unless they have made some updates recently, it should work.

On vie, dic 4, 2015 at 2:43 AM, PeterKaminski09/baskup
<reply@reply.github.com>
wrote:
Running under Yosemite I get (asterisks added to protect the innocent)-

user (master ) baskup-master $ bash baskup.sh

mkdir: +614 *** : File exists
mkdir: Attachments: File exists
backUpMessages.sh: line 44: iMessage;-;+614 * : command not found
usage: mkdir [-pv] [-m mode] directory ...
mkdir: Attachments: File exists
backUpMessages.sh: line 44: +614 *** : command not found
mkdir: can ***** @126.com: File exists
mkdir: Attachments: File exists
backUpMessages.sh: line 44: iMessage;-;can *******@126.com: command not found

etc
