### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SethCalkins** [PeterKaminski09/baskup#8]
# Feature Request
## Problem
- Over the years, I have installed many fresh copies of OS X. Every time I have installed a new Operating system I have saved the contents of ~/Library/Messages.
- After exploring the sqlite files, I have realized that many of them overlap causing duplicates)
## Solution
- Ability to unify / merge multiple iMessage backups into one backup solution. 
## Bonus Feature
- Ability to restore unified backup

**Comment by PeterKaminski09** [comment]
Great idea Seth. I have a solution for that in the macOS app--but it makes a folder for each back up, and it only continues to back up any messages that are past the date of the last backup. I'm not sure how I could extend that to specific backup files. I've stopped development on the script in favor of the Mac app. But the overall logic is not that different.

**Comment by SethCalkins** [comment]
I'm 👍🏻 with desktop app as long as this feature is implemented 😆 So, their is in existing macOS app (Chatology) that does a very good job at locating any and all chat.db files (even if it's on a mounted AFP share) by utilizing a daemon that watches console.log (for what exactly I'm still figuring that out) and combines, and weeds out the duplicates into its own protected /private SQLite database.. 

Problem is.. This database is not accessible for the purpose of backup / combine .. It's only used to search for previous messages...

With no help from the developer of Chatology I'm going to work on reverse engineering this app to figure out what makes it tick.. I'll provide a repo with my findings, and if it provides any use for you to implement it into your desktop app feel free to use it..
